import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Nav } from "@/components/nav";
import { ToastContainer } from "react-toastify";
import { auth, currentUser } from "@clerk/nextjs/server";
import db from "@/lib/db";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  if (userId) {
    const authUser = await currentUser();

    const user = await db.user.findUnique({
      where: {
        userId,
      },
    });

    if (!user) {
      await db.user.create({
        data: {
          email: String(authUser?.emailAddresses[0].emailAddress),
          userId: userId,
          name: authUser?.lastName || authUser?.firstName,
        },
      });
    }
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div>
            <Nav />
          </div>

          <div className="flex flex-col mx-auto w-[650px] p-4 space-y-4">
            <ToastContainer />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
